/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'aclAuthMethod', { get: function () { return require('./acl-auth-method'); } });
Object.defineProperty(exports, 'aclBindingRule', { get: function () { return require('./acl-binding-rule'); } });
Object.defineProperty(exports, 'aclPolicy', { get: function () { return require('./acl-policy'); } });
Object.defineProperty(exports, 'aclRole', { get: function () { return require('./acl-role'); } });
Object.defineProperty(exports, 'aclToken', { get: function () { return require('./acl-token'); } });
Object.defineProperty(exports, 'csiVolume', { get: function () { return require('./csi-volume'); } });
Object.defineProperty(exports, 'csiVolumeRegistration', { get: function () { return require('./csi-volume-registration'); } });
Object.defineProperty(exports, 'externalVolume', { get: function () { return require('./external-volume'); } });
Object.defineProperty(exports, 'job', { get: function () { return require('./job'); } });
Object.defineProperty(exports, 'namespace', { get: function () { return require('./namespace'); } });
Object.defineProperty(exports, 'nodePool', { get: function () { return require('./node-pool'); } });
Object.defineProperty(exports, 'quotaSpecification', { get: function () { return require('./quota-specification'); } });
Object.defineProperty(exports, 'schedulerConfig', { get: function () { return require('./scheduler-config'); } });
Object.defineProperty(exports, 'sentinelPolicy', { get: function () { return require('./sentinel-policy'); } });
Object.defineProperty(exports, 'variable', { get: function () { return require('./variable'); } });
Object.defineProperty(exports, 'volume', { get: function () { return require('./volume'); } });
Object.defineProperty(exports, 'dataNomadAclPolicies', { get: function () { return require('./data-nomad-acl-policies'); } });
Object.defineProperty(exports, 'dataNomadAclPolicy', { get: function () { return require('./data-nomad-acl-policy'); } });
Object.defineProperty(exports, 'dataNomadAclRole', { get: function () { return require('./data-nomad-acl-role'); } });
Object.defineProperty(exports, 'dataNomadAclRoles', { get: function () { return require('./data-nomad-acl-roles'); } });
Object.defineProperty(exports, 'dataNomadAclToken', { get: function () { return require('./data-nomad-acl-token'); } });
Object.defineProperty(exports, 'dataNomadAclTokens', { get: function () { return require('./data-nomad-acl-tokens'); } });
Object.defineProperty(exports, 'dataNomadAllocations', { get: function () { return require('./data-nomad-allocations'); } });
Object.defineProperty(exports, 'dataNomadDatacenters', { get: function () { return require('./data-nomad-datacenters'); } });
Object.defineProperty(exports, 'dataNomadDeployments', { get: function () { return require('./data-nomad-deployments'); } });
Object.defineProperty(exports, 'dataNomadJob', { get: function () { return require('./data-nomad-job'); } });
Object.defineProperty(exports, 'dataNomadJobParser', { get: function () { return require('./data-nomad-job-parser'); } });
Object.defineProperty(exports, 'dataNomadNamespace', { get: function () { return require('./data-nomad-namespace'); } });
Object.defineProperty(exports, 'dataNomadNamespaces', { get: function () { return require('./data-nomad-namespaces'); } });
Object.defineProperty(exports, 'dataNomadNodePool', { get: function () { return require('./data-nomad-node-pool'); } });
Object.defineProperty(exports, 'dataNomadNodePools', { get: function () { return require('./data-nomad-node-pools'); } });
Object.defineProperty(exports, 'dataNomadPlugin', { get: function () { return require('./data-nomad-plugin'); } });
Object.defineProperty(exports, 'dataNomadPlugins', { get: function () { return require('./data-nomad-plugins'); } });
Object.defineProperty(exports, 'dataNomadRegions', { get: function () { return require('./data-nomad-regions'); } });
Object.defineProperty(exports, 'dataNomadScalingPolicies', { get: function () { return require('./data-nomad-scaling-policies'); } });
Object.defineProperty(exports, 'dataNomadScalingPolicy', { get: function () { return require('./data-nomad-scaling-policy'); } });
Object.defineProperty(exports, 'dataNomadSchedulerConfig', { get: function () { return require('./data-nomad-scheduler-config'); } });
Object.defineProperty(exports, 'dataNomadVariable', { get: function () { return require('./data-nomad-variable'); } });
Object.defineProperty(exports, 'dataNomadVolumes', { get: function () { return require('./data-nomad-volumes'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

